# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      # Allow updates for Lodash
      - dependency-type: "all"
      # Allow updates for React and any packages starting "react"
      - dependency-name: "@prisma/client"
      - dependency-name: "nodemon"
      - dependency-name: "express"
      - dependency-name: "dotenv"
      - dependency-name: "mysql"
      - dependency-name: "prisma"
